### ISSUE TITLE
adding a new table for invite codes that are for teachers

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2018-ZeeguuDashboard#171]
@Oli26 - we discussed about how to ensure that a user is a teacher. 
but the discussion is open to everybody not only Oli: 

- one possibility that just occurred to me is to have a separate table invite_codes which lists the active invite codes together with an extra column specifying whether a code is valid for a teacher or for a student. 

what do you think/?

**Comment by Oli26** [comment]
I don't understand how this would work to prevent users creating class rooms. A list of active invite codes is already existing as the cohort table. I think we need a database that holds all users who are currently teachers. This way when a user tries to create a class, we attempt to link that users id to an id in the teacher (whitelist) table. 
In general the invite_codes are not that important in the system, they only have impact when the user initially joins the cohort. From that point on, all linking is done through cohort_id.

**Comment by mircealungu** [comment]
Hmm. I had in mind joining the `User.invite_code` with `InviteCode.isTeacher` in order to know if a user is a teacher or not. 

But you are right, a teachers table where we have (id, user_id) would serve the same goal and be more straightforward.

**Comment by Oli26** [comment]
Converted the teacher object in the db to a table that now stores teachers.
Users need to be on this teacher list to create a cohort.
