### ISSUE TITLE
HIGH: Filtering class information by date:

### ISSUE THREAD

**Issue by Oli26** [RUGSoftEng/2018-ZeeguuDashboard#50]
1 w (default)
2 w
1 m
6 m
1 y
Let the last filter stay the same the next time the user logs in.

**Comment by henryhs97** [comment]
https://github.com/RUGSoftEng/2018-ZeeguuDashboard/tree/feature/filtering_class_info_by_date
here is so far what i got

**Comment by henryhs97** [comment]
DONE!
