### ISSUE TITLE
web uses obsolete endpoint?

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2018-ZeeguuDashboard#64]
i know you know about this, but i'll put it here, so i'm notified when it's fixed. 

after using /login i go to the root of the website, i' redirected to /teacher and then I get a 500 Internal Server Error. 

looking at the output of the API I see that it calls /has_session. 
this endpoint does not exist in the latest version of the API anymore
use /validate instead.

```
127.0.0.1 - - [26/Apr/2018 22:20:21] "POST /session/i@mir.lu HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2018 22:20:25] "GET /has_session?session=37658269 HTTP/1.1" 404 -

```

**Comment by Oli26** [comment]
Sorry about that, the API_Update was still waiting to be merged into development.
Development is updated now and it should work!
